### ISSUE TITLE
iOS - fatal error: 'moengage_flutter/moengage_flutter-Swift.h' file not found

### ISSUE THREAD

**Issue by sam0829** [moengage/Flutter-SDK#19]
Hello,

I am getting the following error while running on the iOS and it's not getting compiled successfully:

```
/flutter/.pub-cache/hosted/pub.dartlang.org/moengage_flutter-4.0.0/ios/Classes/MoEngageFlutterPlugin.m:2:9: fatal error: 'moengage_flutter/moengage_flutter-Swift.h' file not found
    #import <moengage_flutter/moengage_flutter-Swift.h>
```

MoEngage Flutter SDK Version: `4.0.0`
Flutter - `(Channel stable, 2.2.1, on macOS 11.2.3 darwin-x64, locale en-IN)`
Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • `Xcode 12.4`, Build version 12D4e
    • CocoaPods version `1.10.1`

Please LMK if more details are needed.

**Comment by umangmoe** [comment]
Stale issue, closing
