### ISSUE TITLE
In App Campaign Issue

### ISSUE THREAD

**Issue by rahuldange09** [moengage/Flutter-SDK#4]
In App campaign only pushes notification and after clicking notification app opens but In App Banner not coming.
It only worked once. Then after it's not working.
I tried with test on both environment same result.

Please have a look at it

**Comment by umangmoe** [comment]
Please reach out to support@moengage.com with details like account name, the platform on which you are facing this issue etc.

**Comment by rahuldange09** [comment]
Thank you for reply.
It seems it works but not everytime specially when app is open and clicks on notification.
And another thing is that do I have to do this for android
`    optOutDefaultInAppDisplay()
`  
in application class to receive in app native ?
