### ISSUE TITLE
Latest Flutter SDK does not support MoEngage Android SDK versions 12.x.x

### ISSUE THREAD

**Issue by GreatGatsby108** [moengage/Flutter-SDK#43]
Recently, a mail was sent by the MoEngage team stating that due to Google policy changes regarding the collection of advertiser IDs, all users were to add the related permission to the AndroidManifest as well as upgrade to the latest MoEngage Android SDK (which at the time of writing this is 12.2.03).

However, the current latest Flutter SDK (v4.2.0) uses a MoEngage SDK version of 11.6.02. As the 11.x.x and 12.x.x Android SDK classes have significant changes between them, upgrading the Android SDK causes the registration of the Flutter SDK plugin to fail.

Kindly upgrade the Android SDK dependency within the Flutter plugin ASAP, as the deadline to upgrade to the policy compliant SDK is 31/08/2022.

I've quoted the contents of the above stated mail from the MoEngage team below:

> Due to a recent update in the User Data Policy by Google, some of you might have received an email from Google saying “Your app includes non-compliant SDK”. We wanted to write to you about why this is happening and how can this be resolved.
Google Data Policy 
</br>Why did you receive that email?
</br>MoEngage SDK generates a persistent device identifier to uniquely identify the user to deliver personalised engagement. MoEngage SDKs versions 12.0.00 and lower track advertising identifier by default and map it against the persistent identifier. 
</br>As part of the Google User Data policy update in April 2022, this method of mapping is against the latest User Data Policy. With this update,  you would need to get explicit consent from the user to connect personally-identifiable information with the advertising ID. For more information on the new policy please refer to our [user guide.](http://url1445.product.moengage.io/ss/c/XmAKLnGGCmJSynDk37Y5vSXPsi5lm1P_ReCcoNYejzUuvuOWV10xFmiSe7Tba32hHeHLwc268oTz94rYzNhoDBtpHM17bXEjw6fl2eI_5Ro6eBVgMunazGRnulFQay3WvU4f6kb_f99osdrK8KmCpwWPoNdOhpspJ9aTNjA_QH9BKlPny3STiofjyv6MkS4Ej55bJPNs4wZf3N96YYsc401vmWeg3rg6tTpxwDgm_MiDDBn9pZz6YA4cvnpYCaaBdvMSkfHTz8fcrZdkUw7Po2_gyGcxY-Zlo4wK2l9IJdnFZv1E1KqdGd54n4-tXcEBMri8UFImF-Ol-hezi9cbv9JiYsK9S04xPIaI08b6mx8bcWyG-QZelW-KCc-reuwB4V23ODW3XAf3mbYY1VPAn1jvN0JQg1Ev9ej5N9O-JrTs5KiWUxn1lzDDEN0ZCzFWQNG55gB4Xl7bjfd508pPvE3Z5-3V-aIvQeQXHYYI_Rd3eA2KvJaCT-AbP9QjM3HKnCHVZG9_fCisRCXDCTNwKw1zzCLRzzcQMaqzTDC75T7YqJ8emGdXoA1KrU1gFU3ddpNYkC9cGj7qMb-fdjnNI1U0Z2kVH-JRyGBgmfYh5Up3hYbdIVJPZUzQem2ifmIaSx_QYARgfocwarRsgKaDFsKIjbk8BruFD7G-Xh2UPrYKMqWcgeBI8ryT3wM5LBvRziqxbelPgHeNGC9pUSPTDcwKe1lkxhcITfLROgLcqT1Z_Keu3D0wChZNY5UhG2Ik-RcC45V_YOm33UOoxEhJLEIfB3mG-zuK1JxNlwJgV7kGfZl7Fwqxh3khF-mqguDXq4tX8K8OvwjIlqdd42YD2mQvFEwJESzIR9SixLplIQnMJhD_s9nyJwItIuMsbmrJYJH47enbvc58puLecvtLR1AVXP0C4GFZPoUcoMBssKCkexgfFBX68Vag95JOTf4LpOPsnHPFrzQgB3iLLgZwe85lJiRo-l-BE_LrJ60TRFFh7f_Sc9CDdu-DWrA_1hQUehZEH8iAzFA-ryxuyO3ozzFmvGnTW8JAHqzulnTJnkCR6CMVk5lTZgc12x_2uJs9ZnbaRPECTuMh9suLjBwNBFX4tDGHCkw0kGFIxHI138u_Jl_1Vlf1FpdBmqDUViniw3QwhlpPzKm1gdeodzPalg/3ng/ER2sfWUdR7KJyAw822ZTNg/h1/nb0FfWvz8YDaAXWRmIBtV74utqXU1Mrz1JHHgLpPuuk)
</br>Why does MoEngage need Android Advertising ID Tracker (AAID)?
MoEngage optionally accepts AAID (Android Advertising ID Tracking) through user permission. This is associated with unique user identifiers for accurate analytics around devices. This allows us to:
> -   Keep an accurate identification of reachable devices for sending push notifications. 
> -  Track re-installs for users over time.

> What do you have to do to comply with this policy?
</br>MoEngage complies with the guidelines mentioned under Google Play Developer Program Policy and has built industry-standard APIs in the SDKs which enables you to access and track user data only after explicit consent from the user. All you have to do is update your SDKs to enable the advertising identifier tracking. 
</br>Here’s how to enable the Advertising Identifier Tracking:
> - If you are on Andriod Native, please refer to the developer doc on [Enabling Advertising ID tracking](http://url1445.product.moengage.io/ss/c/XmAKLnGGCmJSynDk37Y5vSXPsi5lm1P_ReCcoNYejzUuvuOWV10xFmiSe7Tba32hHeHLwc268oTz94rYzNhoDBtpHM17bXEjw6fl2eI_5Ro6eBVgMunazGRnulFQay3WvU4f6kb_f99osdrK8KmCpwWPoNdOhpspJ9aTNjA_QH9BKlPny3STiofjyv6MkS4Ej55bJPNs4wZf3N96YYsc401vmWeg3rg6tTpxwDgm_MiDDBn9pZz6YA4cvnpYCaaBdvMSkfHTz8fcrZdkUw7Po2_gyGcxY-Zlo4wK2l9IJdnFZv1E1KqdGd54n4-tXcEBbnNJUnPO1KpfPNIYb5l80TQjxLRcJjHdtGVBGWwHZ_j5csYQeHvoXTwNWgC3PJTOI6-Vl8-w4fHKXCVOnNYaKzhBXxQIXsr7bunnxx0b45r3lVddaOD2klP4NCu5EvHKnYiOViPrtn4W8hL6HClbkKaJpKXos5hr3HZKxNFqF1o1Hs_kpGNPxb4L8MyU3j7RYu74emSCdR7bejUGfj2qp7G_UlV0N261vn_thb7006KxkkkZ0tP6Q9b1oNE9aajGUGHko_JNg034kH7keyv89Mxhs_xoXJNYBbCXbHccbUMquKdOf1wKha9MQvf4rVuyXsk213S50fqfv1eQg70gkh9ilcsMzr8yQMtP3IEm2K2EVvYLhnpuWxt7ey6I1kySny_kUX0mL7CH1JbbfwQ6c_ScnMCrvN6lC_X_SQtktxdwhohVUMB_S1cJISBsUM4PqPEPHFyl2RcYY-fjob9hzWmITu1-nkQtISOP_95nuBuArKD0DhGBufyUvLN2X1FxERQ3JmTSwFtmPsQN9d9in_mL-oIGiAUl4AmgjdFuki0NCLiI7iT6m1bbB-P9crf6lAoOqi5kplbbNEGeKhiD0pPirdxfo2kw9Eme9tUBDwzPmFK9OfePTdxoQtoOYQYaTmFJ-YrrIggA04NOFGNK4NtxiphAlXXYTOWAPUjqhxHsPKWKQ6LkfVoGZ0T8QOXHbIeFfht9B_cvrFq_kUNyqvRaWtx1LLVzEyX5m5nRGF3sGzy47aV6qNVTos6aNYrTtOVD1l1DzI1gDe9--ZiVile-oRbZF8KdpKCYlbm6G6XDogty33dwNW7D7781uWNrWSL93BLU_r_qd0Vs8IXaJxeR2qYMBcEcMbUZEAprpO5s-I7SVyfpskxoMYBz-JAflvQlD1gUTt20mPhzlkDMOA/3ng/ER2sfWUdR7KJyAw822ZTNg/h3/rfF0hf8RJQWOO1WbNM28NzdGILIxZmEA7L1r8mHDZ8k).
>- If your app is on any framework other than Android native, please reach out to your MoEngage Customer Success Manager for special assistance or write to us at [support@moengage.com](mailto:support@moengage.com)

>What do we recommend?
We at MoEngage strongly recommend you to update to the latest version so you can continue to track unique user identifiers across devices. Find details on our latest update [here](http://url1445.product.moengage.io/ss/c/XmAKLnGGCmJSynDk37Y5vSXPsi5lm1P_ReCcoNYejzUuvuOWV10xFmiSe7Tba32hHeHLwc268oTz94rYzNhoDBtpHM17bXEjw6fl2eI_5Ro6eBVgMunazGRnulFQay3WvU4f6kb_f99osdrK8KmCpwWPoNdOhpspJ9aTNjA_QH9BKlPny3STiofjyv6MkS4Ej55bJPNs4wZf3N96YYsc401vmWeg3rg6tTpxwDgm_MiDDBn9pZz6YA4cvnpYCaaBdvMSkfHTz8fcrZdkUw7Po2_gyGcxY-Zlo4wK2l9IJdnFZv1E1KqdGd54n4-tXcEBAHmCBZV43FRdzSXWBoqVvNZnGPvhqckzRfzpYDmo5S04br06KRBnnXEZMFCHZXCPA6osXtZYDwEHNtXuZKr_IanFQziseq1XLDyHaQn8ICQXuoSlHWImQYyTdVNmhiVbBwprUWwjZ0uuoUIUP0hAPP0PnBR2y2gPeca07ZLaQkTS2znFHfXYKTOTeAPWsxIrTWtFqCp10-7WP1VZ_mPbOK6MLwS8z7zB10rp4iSXZrFqttoY_LYX7U_bqvzyalWYWK4JWu2MsxdbxqkVsuOSPyQuntLGI4hJB0CZYRcJDr8L4Kme5MuyygA-FOX5s5_Vo-fjg3zxSI-5dv8U4XINidN-Z7P881bqksKRZh4llNGCs9UnQxOBYYyPltsb1R1oT1-ImpC3nfsNZKEbfRmjT_Y6nqCsCiDa8AThlGVB9xSQjdqRpWBcS1i-mGNLUoikARydYLFm8oKrWcZnCyEVKuUBWWYTgBRjEaSoQ7T4KfLqaKH9f-MIy4_51x9Yt4erZYrSZe_2knZ67LBetJiD_yAyfNXpdZGQxPox-vPF05V-NLBxKa1s97YVpV1QYqOduM5R7uD8yuJZbLD-2uqESL9Dmb_WX2aqMOGjBuHw_oIAXa582xXPYEIsiyRDYnSWgxbiuw90vy2g4BVKRCmIeU4N6jw7cUSyFfromZDOiKxplRpIED_ZS2D0eHUIB6eR3JWcXUdbAhJmOd-uvOmTi6mTk0zz3oZ3kDUi6IoSJ70RACwWV85Ljd3v_9iFRqp1f7_08_oJ_iBUp9T7Ci7z5T4RoF3DbdjHRL9prFd-ccaWdObuuLTk86LkyNErGAZ6KmGJK6hR4ZAnh_VYiByYG_EAQ39Ki8dnfROEnVe60--UguGOx8dQqOJJZKVgPKMU/3ng/ER2sfWUdR7KJyAw822ZTNg/h4/stFRrzHvIvEyJ03ZaUVIhAyeRnfbrPqBVrW63c7Z5vU).

**Comment by GreatGatsby108** [comment]
cc: @umangmoe

**Comment by umangmoe** [comment]
@GreatGatsby108 Please update to MoEngage's Flutter Plugin version 4.2.0. We have made the required changes according to the Google Policy.

For further questions or concerns or issues please reach out to our team at support@moengage.com
