### ISSUE TITLE
Can't navigate deeplink push campaign iOS

### ISSUE THREAD

**Issue by chandrabezzo** [moengage/Flutter-SDK#65]
I try to create an app based on example follow the setup at AppDelegate without NotificationService and PushTemplate. I use moengage_flutter version 5.1.1 with firebase package  on the app. Make a simple campaign using basic notification. Set deeplink and the value using Universal Link. When I tap the notification, user always navigate to open the app only. I try to debug the app setPushCallback never called. So, I can't handle by params that received in app.

**Comment by umangmoe** [comment]
@chandrabezzo Please reach out to us at - support@moengage.com

**Comment by chandrabezzo** [comment]
@umangmoe please check your example app

**Comment by rahul-2501** [comment]
Facing the same issue.
