### ISSUE TITLE
AppDelegate moengage_flutter module not found

### ISSUE THREAD

**Issue by esentis** [moengage/Flutter-SDK#96]
Renaming imports is a braking change, please do mention them on CHANGELOG or update the [documentation](https://developers.moengage.com/hc/en-us/articles/4404302013332-iOS-SDK-Initialization#01GP32DEWBARECZSC1ZVFKVN3M) to reflect those changes.
 
The import on AppDelagte has changed from `moengage_flutter` to `moengage_flutter_ios` .

**Comment by msoumya-engg-sdk** [comment]
Thanks @esentis for reporting this, integration documentation has been updated to reflect this change.
